"""Inisialisasi baru

Revision ID: 00b13779b43f
Revises: 
Create Date: 2024-10-29 21:39:01.438222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b13779b43f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategoribarang',
    sa.Column('id_kategori', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_kategori', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_kategori')
    )
    op.create_table('pengguna',
    sa.Column('idpengguna', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_pengguna', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idpengguna')
    )
    op.create_table('supplier',
    sa.Column('id_supplier', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_supplier', sa.String(length=250), nullable=False),
    sa.Column('alamat_supplier', sa.Text(), nullable=True),
    sa.Column('telepon_supplier', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_supplier')
    )
    op.create_table('barang',
    sa.Column('id_barang', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_kategori', sa.BigInteger(), nullable=False),
    sa.Column('nama_barang', sa.String(length=250), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('tanggal_ditambahkan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategoribarang.id_kategori'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_barang')
    )
    op.create_table('transaksikeluar',
    sa.Column('id_transaksi', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_barang', sa.BigInteger(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tanggal_keluar', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id_barang'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_transaksi')
    )
    op.create_table('transaksimasuk',
    sa.Column('id_transaksi', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_barang', sa.BigInteger(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tanggal_masuk', sa.DateTime(), nullable=True),
    sa.Column('id_supplier', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id_barang'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_supplier'], ['supplier.id_supplier'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_transaksi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksimasuk')
    op.drop_table('transaksikeluar')
    op.drop_table('barang')
    op.drop_table('supplier')
    op.drop_table('pengguna')
    op.drop_table('kategoribarang')
    # ### end Alembic commands ###
