"""menghapus kolom id_pengguna dalam tabel transaksimasuk

Revision ID: 05a4e2f446b0
Revises: 140999a27731
Create Date: 2024-10-26 20:35:06.469371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a4e2f446b0'
down_revision = '140999a27731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksikeluar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pengguna', sa.BigInteger(), nullable=False))
        batch_op.create_foreign_key(None, 'pengguna', ['id_pengguna'], ['idpengguna'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksikeluar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_pengguna')

    # ### end Alembic commands ###
