"""mengubah relasi di tabel transaksi masuk dan keluar

Revision ID: 0dfdece211bd
Revises: 213ae539a93a
Create Date: 2024-11-07 10:02:08.811346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dfdece211bd'
down_revision = '213ae539a93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksikeluar', schema=None) as batch_op:
        batch_op.alter_column('id_barang',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.drop_constraint('transaksikeluar_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'barang', ['id_barang'], ['id_barang'], ondelete='SET NULL')

    with op.batch_alter_table('transaksimasuk', schema=None) as batch_op:
        batch_op.alter_column('id_barang',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('id_supplier',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.drop_constraint('transaksimasuk_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('transaksimasuk_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'barang', ['id_barang'], ['id_barang'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'supplier', ['id_supplier'], ['id_supplier'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksimasuk', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaksimasuk_ibfk_2', 'supplier', ['id_supplier'], ['id_supplier'], ondelete='CASCADE')
        batch_op.create_foreign_key('transaksimasuk_ibfk_1', 'barang', ['id_barang'], ['id_barang'], ondelete='CASCADE')
        batch_op.alter_column('id_supplier',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('id_barang',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    with op.batch_alter_table('transaksikeluar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaksikeluar_ibfk_1', 'barang', ['id_barang'], ['id_barang'], ondelete='CASCADE')
        batch_op.alter_column('id_barang',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###
