"""Menghapus kolom kategori dalam tabel barang

Revision ID: 140999a27731
Revises: f88e06757df8
Create Date: 2024-10-26 19:48:53.963338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '140999a27731'
down_revision = 'f88e06757df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_column('kategori')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori', mysql.VARCHAR(length=250), nullable=False))

    # ### end Alembic commands ###
