"""Mengubah relasi barang dan kategori barang

Revision ID: 213ae539a93a
Revises: 00b13779b43f
Create Date: 2024-11-07 09:44:03.182495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '213ae539a93a'
down_revision = '00b13779b43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('id_kategori',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.drop_constraint('barang_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'kategoribarang', ['id_kategori'], ['id_kategori'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('barang_ibfk_1', 'kategoribarang', ['id_kategori'], ['id_kategori'], ondelete='CASCADE')
        batch_op.alter_column('id_kategori',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###
