"""menghapus kolom id_pengguna dalam tabel transaksimasuk dan transaksikeluar

Revision ID: 21753bf48759
Revises: 05a4e2f446b0
Create Date: 2024-10-26 20:45:08.418709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21753bf48759'
down_revision = '05a4e2f446b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksikeluar', schema=None) as batch_op:
        batch_op.drop_constraint('transaksikeluar_ibfk_2', type_='foreignkey')
        batch_op.drop_column('id_pengguna')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksikeluar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pengguna', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('transaksikeluar_ibfk_2', 'pengguna', ['id_pengguna'], ['idpengguna'], ondelete='CASCADE')

    # ### end Alembic commands ###
