"""Membuat tabel barang

Revision ID: 3cc4b5355403
Revises: d4904c824007
Create Date: 2024-10-22 20:42:34.851030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc4b5355403'
down_revision = 'd4904c824007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang',
    sa.Column('id_barang', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_kategori', sa.BigInteger(), nullable=True),
    sa.Column('nama_barang', sa.String(length=250), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('kategori', sa.String(length=250), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('tanggal_ditambahkan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategoribarang.id_kategori'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_barang')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barang')
    # ### end Alembic commands ###
