"""Membuat tabel barang

Revision ID: 3f25b8d98c42
Revises: 3cc4b5355403
Create Date: 2024-10-22 20:43:39.094335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f25b8d98c42'
down_revision = '3cc4b5355403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('id_kategori',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('id_kategori',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)

    # ### end Alembic commands ###
