"""Membuat tabel transaksimasuk

Revision ID: 45612bebf8b1
Revises: 55d5ede1a0c6
Create Date: 2024-10-22 20:48:53.409952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45612bebf8b1'
down_revision = '55d5ede1a0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaksimasuk',
    sa.Column('id_transaksi', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_barang', sa.BigInteger(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tanggal_masuk', sa.DateTime(), nullable=True),
    sa.Column('id_supplier', sa.BigInteger(), nullable=False),
    sa.Column('id_pengguna', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id_barang'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.idpengguna'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_supplier'], ['supplier.id_supplier'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_transaksi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksimasuk')
    # ### end Alembic commands ###
