"""Membuat tabel kategori barang

Revision ID: c508bbd07373
Revises: c81c13a2464c
Create Date: 2024-10-22 20:26:24.319621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c508bbd07373'
down_revision = 'c81c13a2464c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategoribarang',
    sa.Column('id_kategori', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_kategori', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_kategori')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kategoribarang')
    # ### end Alembic commands ###
