"""Membuat tabel pengguna

Revision ID: c81c13a2464c
Revises: 
Create Date: 2024-10-22 16:06:55.202296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81c13a2464c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengguna',
    sa.Column('idpengguna', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_pengguna', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idpengguna')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengguna')
    # ### end Alembic commands ###
