"""Membuat tabel pengguna dan kategoribarang

Revision ID: d4904c824007
Revises: c508bbd07373
Create Date: 2024-10-22 20:40:25.978213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4904c824007'
down_revision = 'c508bbd07373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategoribarang',
    sa.Column('id_kategori', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_kategori', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_kategori')
    )
    op.create_table('pengguna',
    sa.Column('idpengguna', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_pengguna', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idpengguna')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengguna')
    op.drop_table('kategoribarang')
    # ### end Alembic commands ###
