"""Membuat tabel transaksikeluar

Revision ID: f88e06757df8
Revises: 45612bebf8b1
Create Date: 2024-10-22 20:49:54.329758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88e06757df8'
down_revision = '45612bebf8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaksikeluar',
    sa.Column('id_transaksi', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_barang', sa.BigInteger(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tanggal_keluar', sa.DateTime(), nullable=True),
    sa.Column('id_pengguna', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id_barang'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.idpengguna'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_transaksi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksikeluar')
    # ### end Alembic commands ###
